name: Daily Compatibility Test

on:
  # for tests only, on every push, will remove later
  push:

  # schedule:
  #   # This is scheduled to run every day at midnight
  #   - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Setup Environment
      run: |
        sudo apt update
        sudo apt install -y pkg-config build-essential libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make libprotobuf-dev protobuf-compiler

    - name: Install AVM and Latest Anchor CLI
      run: |
        cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
        avm install latest
        avm use latest

    - name: Install stable Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Generate Keypair File
      run: |
        solana-keygen new --outfile keypair.json --no-bip39-passphrase --force

    - name: Test project with latest Anchor version and stable Solana CLI
      run: |
        anchor build

    - name: Test project with master Anchor version and stable Solana CLI
      run: |
        git clone https://github.com/coral-xyz/anchor.git
        cd anchor/cli
        cargo build --release
        cd ../..
        ./anchor/target/release/anchor build

    - name: Test project with latest Anchor version and master Solana CLI
      run: |
        git clone https://github.com/solana-labs/solana.git
        cd solana/cli
        cargo build --release
        cd ../target/release
        ./solana --version

        cd ../../../..
        anchor build

    - name: Test project with latest Anchor version and beta Solana CLI
      run : |
        sh -c "$(curl -sSfL https://release.solana.com/beta/install)"
        echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        solana --version

        anchor build

